
### Start process with businessKey, which should be unique
GET /engine-rest/deployment/ HTTP/1.1
Host: localhost:8080
Content-Type: application/json


### Start process with businessKey, which should be unique
delete /engine-rest/deployment/2f223a68-88bd-11ea-a09e-207918df83ec?cascade=true HTTP/1.1
Host: localhost:8080
Content-Type: application/json



### Start process with businessKey, which should be unique
POST /engine-rest/process-definition/key/einarbeiter/start HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
	"variables": {
		"amount": {
			"value":555,
			"type":"string"
		},
		"item": {
			"value": "item-aab"
		}
	},
 	"businessKey" : "4713"
}



### Start process with businessKey, which should be unique
POST /engine-rest/process-definition/key/einarbeiter/start HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "variables": {
        "broker": {
            "value": "{\"name\":\"Broker Name\"}",
            "type": "json"
        }
    },
 	"businessKey" : "7777"
}



### reading all instances with given business-Key
GET /engine-rest/process-instance/?businessKey=4711 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
	"variables": {
		"amount": {
			"value":555,
			"type":"long"
		},
		"item": {
			"value": "item-aab"
		}
	},
 	"businessKey" : "4711"
}


### reading all instances with given business-Key
GET /engine-rest/process-definition/key/Einarbeiter HTTP/1.1
Host: localhost:8080
Content-Type: application/json




### reading all instances with givenprocessDefintion-Key and business-Key
//GET /engine-rest/process-instance/count?processDefinitionKey=einarbeiter HTTP/1.1
GET /engine-rest/process-instance/count?businessKey=4713&processDefinitionKey=einarbeiter&variables=firma_eq_AL HTTP/1.1
Host: localhost:8080
Content-Type: application/json



### GET all processDefinitions

GET /engine-rest/process-definition HTTP/1.1
Host: localhost:8080
Content-Type: application/json